### ISSUE TITLE
Add MA Logo and "Newsletter" Text on top of each newsletter

### ISSUE THREAD

**Issue by chrbertsch** [modelica/newsletter#244]
... so that it gets nicely previewd when re-posted on social media, e.g. LinkedIn.

e.g. something like
![image](https://user-images.githubusercontent.com/16363372/223061895-25686739-0f50-4ca4-bd4f-87e0f47518f2.png)

**Comment by filip-jezek** [comment]
You mean like integrating the text into the image directly? That might be a good idea. What about this?

![Modelica](https://user-images.githubusercontent.com/3962483/223092720-c9e38c1d-1cb9-4b6b-bf19-7585ee06c42a.svg)

**Comment by filip-jezek** [comment]
It is an svg so I can just modify the plaintext each issue. Any comments regarding the fonts / layout would be appreciated. Would that work for these purposes?

**Comment by chrbertsch** [comment]
I would keep the "assciation", as the newsletter deals with all MA standards.

**Comment by filip-jezek** [comment]
Please check the https://newsletter.modelica.org/2023-01/index and if it works with the svg as intended too.

**Comment by chrbertsch** [comment]
The logo is nice!
