### ISSUE TITLE
New categories

### ISSUE THREAD

**Issue by filip-jezek** [modelica/newsletter#26]
So far we stick to four categories. There was a proposal to create category "projects", but since the project1 is the only content I am not strongly persuaded we shall do this. What is your opinion @MartinOtter @xogeny ?

**Comment by xogeny** [comment]
Quite a bit of Modelica related development work has been done via government projects.  So I there will be several such news items (if not in this newsletter, in others).  So I am in favor of adding it.  @MartinOtter ?

**Comment by MartinOtter** [comment]
Yes, there will be similar items in the future, so project information, but also workshops and conferences that are related to Modelica and/or FMI. A category such as "Project, workshop, conference news" might fit, but this is too long. O.k. I agree, just introduce "Project News" and topics related to projects, workshops and conferences (not organized by Modelica Association) shall be added here.

**Comment by filip-jezek** [comment]
I have added "Related projects" category.
