### ISSUE TITLE
Old logo used in preivew on social media

### ISSUE THREAD

**Issue by chrbertsch** [modelica/newsletter#273]
On LinkedIn, in the preview and old Modelica is displayed, see e.g. https://www.linkedin.com/feed/update/urn:li:activity:7109599366696292353?utm_source=share&utm_medium=member_desktop 

I do not know where this logo is taken from ...

![image](https://github.com/modelica/newsletter/assets/16363372/46016c2d-9b7a-431c-b269-906169900b1e)

**Comment by chrbertsch** [comment]
Please use https://github.com/modelica/MA-Logos/blob/master/LowRes/Modelica_Association.png instead

**Comment by chrbertsch** [comment]
Hi @filip-jezek : could you please fix this before the publication of the 2023-3 newsletter? Thanks!

**Comment by filip-jezek** [comment]
Thanks, fixed.

**Comment by chrbertsch** [comment]
Hm. There must still be somewhere the old logo. Preview on LinkedIn still shows: 
![image](https://github.com/modelica/newsletter/assets/16363372/7cf25427-a25e-428e-83ac-a5b042136354)

**Comment by tlk-thermo-mk** [comment]
Christian,
the link to the image goes to https://newsletter.modelica.org/assets/images/ModelicaLogoSq.jpg and I get this 
![grafik](https://github.com/modelica/newsletter/assets/37672218/728e37ec-478b-4b2f-ab75-c90085f6becd)
If this image is the right one, you have to clear your browser cache or at least try another browser to verify. 

Best, Matthias

**Comment by chrbertsch** [comment]
The logo is wrong, should be replaced by https://github.com/modelica/MA-Logos/blob/master/LowRes/Modelica_Association.png
![image](https://github.com/modelica/newsletter/assets/16363372/0b2b7bf8-481b-4a86-8e44-1050bfdec025)

**Comment by filip-jezek** [comment]
Thank you for the catch. I have replaced the img in the Mailchimp, which is publishing this post automatically, but apparently this img is taken from page preview. I have fixed that as well, should probably propagate in a while, unless X is caching that.

Hopefully closing for good now :)
