### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by beutlich** [modelica/newsletter#274]
https://newsletter.modelica.org/2023-MC/index#modelica-conference-2023-in-aachen and https://newsletter.modelica.org/2023-MC/index#invitation-from-local-organizers seems to be duplicated content where only the first link is listed in the TOc, but the second links seems properly formated.

**Comment by filip-jezek** [comment]
Fixed. It is just not listed in TOC, as it is part of the Letter. Current setup makes it complicated to do otherwise.
