### ISSUE TITLE
References within the newsletter

### ISSUE THREAD

**Issue by beutlich** [modelica/newsletter#32]
Make sure that cross-references within the newsletter work, for example
https://github.com/modelica/newsletter/blob/ef99ee53af2be0e2eb8e12a0ae971a9dd789478b/_2018-01/Letter-from-the-Board.md#L41

**Comment by filip-jezek** [comment]
Generally, this is very hard to find. I would be special careful with the letters from the board, otherwise the artcles do not have to reference themselves.

**Comment by filip-jezek** [comment]
The link has been fixed, of course.
