### ISSUE TITLE
MOdelon contribution to the newsletter - request for revision

### ISSUE THREAD

**Issue by filip-jezek** [modelica/newsletter#35]
Hi Jesse @jbgohl , 
regarding the pr #27 , do you agree to remove the invitation to the mailing list? I think that invitations to other mailing lists does not fit into newsletter. It is okay to respond here, I would do that for you, or you can change it in your branch and commit a pull request.

Thanks!

PS. without your reponse by Friday, I would remove it on my own.

**Comment by jbgohl** [comment]
Hi Filip,
removing the invitation is fine.
Thanks.

**Comment by filip-jezek** [comment]
Thanks for your reply and consent!
F/
