### ISSUE TITLE
Shorten the title

### ISSUE THREAD

**Issue by filip-jezek** [modelica/newsletter#43]
Hi, @wischhusen , regarding PR #22, would you please consider to shorten the title to "FluidDynamics Library for Coarse-Grid-CFD Simulations"? Currently it is the longest title in the newsletter. I could do it for you, if you agree.
Thanks!
F/

**Comment by wischhusen** [comment]
Hi Filip,
hard. Each word is relevant. Eventually we could go with leaving out "Coarse-Grid-". Wdyt?

**Comment by filip-jezek** [comment]
Still longest, but better, at least :) 
Done, closing the issue.
